"""initial middleware schema"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    processing = postgresql.ENUM("pending", "processing", "processed", "succeeded", "failed", "dead_letter", name="processingstatus", create_type=False)
    direction = postgresql.ENUM("inbound_from_roxor", "outbound_to_roxor", name="filedirection", create_type=False)
    processing.create(op.get_bind(), checkfirst=True); direction.create(op.get_bind(), checkfirst=True)
    op.create_table("processed_files", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("filename", sa.String(512), nullable=False), sa.Column("remote_path", sa.String(1024), nullable=False), sa.Column("archive_path", sa.String(1024)), sa.Column("file_hash", sa.String(64), nullable=False), sa.Column("idoc_type", sa.String(32), nullable=False), sa.Column("direction", direction, nullable=False), sa.Column("status", processing, nullable=False), sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("error_message", sa.Text()), sa.Column("correlation_id", sa.String(64), nullable=False), sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False), sa.Column("processed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_processed_files_file_hash", "processed_files", ["file_hash"], unique=True); op.create_index("ix_processed_files_correlation_id", "processed_files", ["correlation_id"]); op.create_index("ix_processed_files_status_first_seen", "processed_files", ["status", "first_seen_at"])
    op.create_table("integration_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("correlation_id", sa.String(64), nullable=False), sa.Column("event_type", sa.String(128), nullable=False), sa.Column("level", sa.String(16), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("duration_ms", sa.Integer()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_integration_logs_correlation_id", "integration_logs", ["correlation_id"])
    op.create_table("order_mappings", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("shopify_order_id", sa.String(128), nullable=False), sa.Column("shopify_order_name", sa.String(128), nullable=False), sa.Column("shopify_customer_id", sa.String(128)), sa.Column("roxor_order_reference", sa.String(128)), sa.Column("roxor_delivery_reference", sa.String(128)), sa.Column("invoice_number", sa.String(128)), sa.Column("invoice_total", sa.Numeric(14, 2)), sa.Column("invoice_currency", sa.String(3)), sa.Column("status", sa.String(64), nullable=False), sa.Column("last_error", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_order_mappings_shopify_order_id", "order_mappings", ["shopify_order_id"], unique=True); op.create_index("ix_order_mappings_shopify_order_name", "order_mappings", ["shopify_order_name"]); op.create_index("ix_order_mappings_roxor_order_reference", "order_mappings", ["roxor_order_reference"]); op.create_index("ix_order_mappings_invoice_number", "order_mappings", ["invoice_number"])
    op.create_table("retry_queue", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("operation_type", sa.String(128), nullable=False), sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("correlation_id", sa.String(64), nullable=False), sa.Column("status", processing, nullable=False), sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"), sa.Column("max_attempts", sa.Integer(), nullable=False, server_default="5"), sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False), sa.Column("last_error", sa.Text()), sa.Column("locked_at", sa.DateTime(timezone=True)), sa.Column("locked_by", sa.String(128)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_retry_queue_status_next_attempt", "retry_queue", ["status", "next_attempt_at"]); op.create_index("ix_retry_queue_correlation_id", "retry_queue", ["correlation_id"])
    op.create_table("inventory_mappings", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("sku", sa.String(255), nullable=False), sa.Column("shopify_variant_id", sa.String(128)), sa.Column("shopify_inventory_item_id", sa.String(128), nullable=False), sa.Column("shopify_location_id", sa.String(128), nullable=False), sa.Column("last_known_quantity", sa.Integer()), sa.Column("last_synced_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("sku", "shopify_location_id", name="uq_inventory_sku_location"))
    op.create_index("ix_inventory_mappings_shopify_inventory_item_id", "inventory_mappings", ["shopify_inventory_item_id"])

def downgrade() -> None:
    op.drop_table("inventory_mappings"); op.drop_table("retry_queue"); op.drop_table("order_mappings"); op.drop_table("integration_logs"); op.drop_table("processed_files")
    postgresql.ENUM(name="filedirection").drop(op.get_bind(), checkfirst=True); postgresql.ENUM(name="processingstatus").drop(op.get_bind(), checkfirst=True)
